title: Wild Bites
subtitle: Fame di natura? Qui ti offriamo sfiziosi bocconcini di <strong style="color:#2E8B57;">natura</strong> e <strong style="color:#2E8B57;">biodiversità</strong>, conditi con un po'
          <strong style="color:#2E8B57;">conservazione</strong>
description: Siamo due laureati in Ecologia ed Etologia per la conservazione della natura. Qui, desideriamo raccontarvi la nostra più grande passione: la natura. Con post e approfondimenti vi racconteremo novità interessanti, aggiornamenti sui lavori di scienziati e ricercatori per la tutela della biodiversità e curiosità sulle meravigliose specie animali che abitano il nostro pianta!         
theme: minima
